# конфиг для alert rules
groups:
  - name: lab-host-alerts # группа alert rules для lab-host
    rules:
      - alert: HighCpu # алерт для высокой загрузки CPU
        expr: job:lab_host_node:node_cpu_idle:rate1m < 0.4 # idle < 40% = CPU > 60%
        for: 1m # как долго должна быть высокая загрузка CPU
        labels:
          severity: warning # severity алерта
          service: lab-host # service для алерта
        annotations:
          summary: "Высокая загрузка CPU на {{ $labels.instance }}" # summary для алерта
          description: "CPU > 60% более 1 минуты (job={{ $labels.job }})" # description для алерта
